# Generated by Django 4.0.1 on 2022-02-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mandal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyakram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('Start_date', models.DateTimeField(blank=True, null=True)),
                ('End_date', models.DateTimeField(blank=True, null=True)),
                ('For_All', models.BooleanField(default=False)),
                ('Mandal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mandal.mandalprofile')),
            ],
        ),
    ]
