# Generated by Django 4.0.1 on 2022-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandal', '0002_karyakram'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyakram',
            name='Karyakram_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
