# Generated by Django 4.0.1 on 2022-02-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mandal', '0003_karyakram_karyakram_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakram',
            name='Mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mandal.mandalprofile'),
        ),
    ]
