# Generated by Django 4.0.1 on 2022-02-03 14:45

import FolloWUp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SamparkKarykar', '0002_karyakarprofile_mandal_alter_karyakarprofile_yuvaks'),
        ('Mandal', '0002_karyakram'),
        ('Yuvak', '0002_yuvakprofile_mandal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowUp_Time', models.DateTimeField(auto_now_add=True)),
                ('LastFollowUp_Time', models.DateTimeField(auto_now=True)),
                ('How', models.IntegerField(choices=[(1, 'Whatsapp'), (2, 'Phonecall'), (3, 'Telegram'), (4, 'SMS'), (5, 'InPerson'), (6, 'Other')], default=FolloWUp.models.HowMethods['Other'])),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('Karyakram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mandal.karyakram')),
                ('SamparkKarykar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SamparkKarykar.karyakarprofile')),
                ('Yuvak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yuvak.yuvakprofile')),
            ],
        ),
    ]
