# Generated by Django 4.0.1 on 2022-02-05 16:21

import FolloWUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'No'), (4, 'InProgress')], default=FolloWUp.models.FollowupStatus['Pending']),
        ),
    ]
