# Generated by Django 4.0.1 on 2022-02-11 11:11

import FolloWUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0002_followup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='Present',
            field=models.IntegerField(choices=[(1, 'Not_Sure'), (2, 'Yes'), (3, 'No'), (4, 'Unknown')], default=FolloWUp.models.PreentStatus['Unknown']),
        ),
    ]
