# Generated by Django 4.0.1 on 2022-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0003_followup_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='SamparkKarykar',
            new_name='KaryKarVrund',
        ),
    ]
