# Generated by Django 4.0.1 on 2022-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0007_rename_present_followup_coming'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='Present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
