# Generated by Django 4.0.1 on 2022-02-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0008_followup_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attandance',
            fields=[
            ],
            options={
                'verbose_name': 'Attandance',
                'verbose_name_plural': 'Attandance',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('FolloWUp.followup',),
        ),
    ]
