# Generated by Django 4.0.1 on 2022-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0010_alter_followup_coming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='FollowUp_Time',
        ),
        migrations.AddField(
            model_name='followup',
            name='Attandance_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='LastFollowUp_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
