# Generated by Django 3.2.12 on 2022-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolloWUp', '0011_remove_followup_followup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='Attandance_Time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entry Time'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='LastFollowUp_Time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Followup Time'),
        ),
    ]
