# Generated by Django 4.0.1 on 2022-02-03 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YuvakProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('SurName', models.CharField(max_length=50)),
                ('WhatsappNo', models.CharField(db_index=True, max_length=10)),
                ('HomePhoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('AddressLine1', models.CharField(max_length=1000)),
                ('AddressLine2', models.CharField(blank=True, max_length=1000, null=True)),
                ('PinCode', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
