# Generated by Django 4.0.1 on 2022-02-01 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Yuvak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuvakprofile',
            name='AddressLine1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='AddressLine2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='Firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='HomePhoneNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='MiddleName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='PinCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='SurName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='WhatsappNo',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
