# Generated by Django 4.0.1 on 2022-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mandal', '0001_initial'),
        ('Yuvak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuvakprofile',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mandal.mandalprofile'),
        ),
    ]
