# Generated by Django 4.0.1 on 2022-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0002_yuvakprofile_mandal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yuvakprofile',
            name='AddressLine1',
        ),
        migrations.RemoveField(
            model_name='yuvakprofile',
            name='AddressLine2',
        ),
        migrations.AddField(
            model_name='yuvakprofile',
            name='Area',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='yuvakprofile',
            name='HouseNo',
            field=models.IntegerField(default=1, verbose_name='House/Flat No.'),
        ),
        migrations.AddField(
            model_name='yuvakprofile',
            name='LandMark',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='yuvakprofile',
            name='Soc_Name',
            field=models.CharField(default='a', max_length=50, verbose_name='Sociaty/Apartment Name'),
        ),
    ]
