# Generated by Django 4.0.1 on 2022-02-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0002_alter_yuvakprofile_addressline1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yuvakprofile',
            old_name='Firstname',
            new_name='FirstName',
        ),
    ]
