# Generated by Django 4.0.1 on 2022-02-08 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0007_alter_yuvakprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satsangprofile',
            name='AthvadikSabha',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='AthvadikSabhaYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Ekadashi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='EkadashiYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='GharSatsang',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='GharSatsangYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='NityaPuja',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='NityaPujaYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Niymit_Vanchan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Niymit_VanchanYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Ravisabha',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='RavisabhaYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='SSP',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Satsangi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='SatsangiYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='TilakChandlo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='TilakChandloYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='Married',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
