# Generated by Django 4.0.1 on 2022-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0008_alter_satsangprofile_athvadiksabha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuvakprofile',
            name='Area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='HouseNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='House/Flat No.'),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='LandMark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yuvakprofile',
            name='Soc_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sociaty/Apartment Name'),
        ),
    ]
