# Generated by Django 4.0.1 on 2022-02-10 08:35

import csv
from django.db import migrations

from Yuvak.models import YuvakProfile


def load_initial_data(apps, schema_editor):
    # get the correct versions of models using the app registry
    Yuvak = apps.get_model("Yuvak", "YuvakProfile")
    mandal = apps.get_model("Mandal","MandalProfile")
    yuvakmandal = mandal.objects.filter(Name="Utsav").first()
    print(yuvakmandal)
    # This is where your migration logic will go. 
    # transform data from the csv file into the schema i wanted 
    with open('yuvaks.csv') as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)
        
        for row in reader:
            print(row)
            yuvak = YuvakProfile(FirstName=row[0],MiddleName=row[1],SurName=row[2],WhatsappNo=row[3],mandal_id=yuvakmandal.pk)
            yuvak.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0009_alter_yuvakprofile_area_alter_yuvakprofile_houseno_and_more'),
    ]

    operations = [
         migrations.RunPython(load_initial_data)
    ]
