# Generated by Django 4.0.1 on 2022-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0015_alter_yuvakprofile_mandal'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuvakprofile',
            name='ProfilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
