# Generated by Django 4.0.1 on 2022-03-03 17:25

import Yuvak.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0016_yuvakprofile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satsangprofile',
            name='AthvadikSabha',
            field=models.BooleanField(blank=True, null=True, verbose_name='અઠવાડિકસભા'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='AthvadikSabhaYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='અઠવાડિકસભા કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Ekadashi',
            field=models.BooleanField(blank=True, null=True, verbose_name='એકાદશી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='EkadashiYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='એકાદશી કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='GharSatsang',
            field=models.BooleanField(blank=True, null=True, verbose_name='ઘરસત્સંગ'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='GharSatsangYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='ઘરસત્સંગ કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='NityaPuja',
            field=models.BooleanField(blank=True, null=True, verbose_name='નિત્યપૂજા'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='NityaPujaYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='નિત્યપૂજા કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Niymit_Vanchan',
            field=models.BooleanField(blank=True, help_text='૧ વચનામૃત અને ૫ સ્વામીની વાતો અથવા પ્રમુખસ્વામી મહારાજ નું જીવન ચરિત્ર વાંચન', null=True, verbose_name='નિયમિત વાંચન'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Niymit_VanchanYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='નિયમિત વાંચન કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Ravisabha',
            field=models.BooleanField(blank=True, null=True, verbose_name='રવિસભા'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='RavisabhaYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='રવિસભા કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='SSP',
            field=models.BooleanField(blank=True, null=True, verbose_name='સત્સંગ શિક્ષણ પરીક્ષા'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='SSPStage',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'prarambh'), (2, 'pravesh'), (3, 'parichay'), (4, 'paravin'), (5, 'Pragn_1'), (6, 'Pragn_2'), (7, 'Pragn_3')], default=Yuvak.models.SSPStage['No'], verbose_name='છેલ્લી પરીક્ષા'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='Satsangi',
            field=models.BooleanField(blank=True, null=True, verbose_name='સત્સંગ'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='SatsangiYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='સત્સંગ કેટલા વર્ષથી'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='TilakChandlo',
            field=models.BooleanField(blank=True, null=True, verbose_name='તિલક ચાંદલો'),
        ),
        migrations.AlterField(
            model_name='satsangprofile',
            name='TilakChandloYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='તિલક ચાંદલો કેટલા વર્ષથી'),
        ),
    ]
