# Generated by Django 3.2.12 on 2022-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0017_alter_satsangprofile_athvadiksabha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevaVibhag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guj_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='yuvakprofile',
            name='current_Education',
            field=models.BooleanField(blank=True, null=True, verbose_name='અભ્યાસ શરુ છે ?'),
        ),
        migrations.AddField(
            model_name='yuvakprofile',
            name='Seva_Intrests',
            field=models.ManyToManyField(blank=True, help_text='જો આપને આમાંથી કોઈ વિભાગ માં રસ હોય તો એ સિલેક્ટ કરી શકશો', to='Yuvak.SevaVibhag', verbose_name='વિશેષ રસ'),
        ),
    ]
