# Generated by Django 3.2.12 on 2022-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0018_auto_20220324_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevavibhag',
            name='guj_name',
            field=models.CharField(max_length=255, verbose_name='Seva Name'),
        ),
    ]
