# Generated by Django 3.2.12 on 2022-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0019_alter_sevavibhag_guj_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevavibhag',
            name='yuvaks',
            field=models.ManyToManyField(blank=True, related_name='seva_yuvaks', to='Yuvak.YuvakProfile'),
        ),
    ]
