# Generated by Django 3.2.12 on 2022-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0021_sevavibhag_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuvakprofile',
            name='Email',
            field=models.EmailField(default='yuvak@utsavmandal.com', max_length=254),
        ),
    ]
