# Generated by Django 3.2 on 2023-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0023_alter_yuvakprofile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuvakprofile',
            name='Soc_Name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sociaty/Apartment Name'),
        ),
    ]
