# Generated by Django 4.0.1 on 2022-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0003_rename_firstname_yuvakprofile_firstname'),
        ('SamparkKarykar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakarprofile',
            name='Yuvaks',
            field=models.ManyToManyField(blank=True, null=True, to='Yuvak.YuvakProfile'),
        ),
    ]
