# Generated by Django 4.0.1 on 2022-02-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamparkKarykar', '0003_alter_karyakarprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyakarprofile',
            name='user',
        ),
    ]
