# Generated by Django 4.0.1 on 2022-02-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Yuvak', '0014_csvtest'),
        ('Mandal', '0005_mandalprofile_nirikshak_mandalprofile_sanchalak'),
        ('SamparkKarykar', '0005_rename_profile_karyakarprofile_karykar1profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyakarprofile',
            name='karykar2profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile2Info', to='Yuvak.yuvakprofile'),
        ),
        migrations.AlterField(
            model_name='karyakarprofile',
            name='karykar1profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile1Info', to='Yuvak.yuvakprofile'),
        ),
        migrations.AlterField(
            model_name='karyakarprofile',
            name='mandal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mandal.mandalprofile'),
        ),
    ]
