# Generated by Django 4.0.1 on 2022-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamparkKarykar', '0006_karyakarprofile_karykar2profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyakarprofile',
            options={'verbose_name': 'KaryKar Vrund'},
        ),
    ]
